name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.3'

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.8.3

    - name: Install project
      run: poetry install --no-interaction

    - name: Create env file
      run: |
        touch .env
        echo SERVICE_EXTERNAL_PORT=5001 >> .env
        echo POSTGRES_USER=postgres >> .env
        echo POSTGRES_PASSWORD=postgres >> .env
        echo POSTGRES_DB=bet_db_test >> .env
        echo POSTGRES_HOST=dev_db >> .env
        echo POSTGRES_PORT=5432 >> .env
        cat .env

    - name: Run tests and build coverage file
      run: |
        poetry run pytest --cov-report=term-missing:skip-covered --cov=app tests/

    - name: Ruff linting
      run: |
        poetry run ruff check .